version: "3.8"
services:
  base:
    image: nolanpro/pm4-ci-base
    build:
      context: .
      dockerfile: Dockerfile.base
  build:
    image: pm4-ci-build:local
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        GITHUB_TOKEN:
        GITHUB_CONTEXT:
        HOST_CACHE_PATH:
  install:
    image: pm4-ci-build:local
    command: sh install-and-test.sh
    volumes:
      - ./pm4-tools:/code/pm4-tools
    env_file:
      - .env
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
  redis:
    image: redis
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  redis:
  pm4:
  pm4-packages: