version: "3.8"
services:
  builder:
    build: .
    env_file:
      - .env
    environment:
      - GITHUB_TOKEN
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      # - storage:/code/pm4/storage
      - ${HOST_CACHE_PATH}:/root/.cache
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
  app:
    image: pm4-app:${PM_VERSION}
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    env_file:
      - .env
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - ${HOST_CACHE_PATH}:/root/.cache
  base:
    image: pm4-base:local 
    build:
      context: .
      dockerfile: Dockerfile.base

  redis:
    image: redis
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  # storage:
  redis: