version: "3.8"
services:
  builder:
    image: nolanpro/pm4-ci-base
    build:
      context: .
      dockerfile: Dockerfile.builder
    command: sh builder.sh
    environment:
      - GITHUB_TOKEN
      - GITHUB_CONTEXT
    env_file:
      - .env
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
    volumes:
      - ./cache:/cache

  redis:
    image: redis
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  redis:
  pm4:
  pm4-packages: