name: Docker Image CI

on:
  push:
    paths:
      - Dockerfile
      - Dockerfile.base
      - .github/workflows/base-test.yml

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: Dockerfile.base
        pull: true
        push: false
        #load: true
        outputs: type=docker,dest=/tmp/myimage.tar
        tags: pm-base:4.1-test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Check Image
      run: |
        #docker pull processmaker/pm4-base:1.0.0
        #docker image ls
        #docker image inspect pm-base:4.1-test
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pm-base
        path: /tmp/pm-base.tar
  pm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: pm-base
        path: /tmp
    - name: Load image
      run: |
        docker load --input /tmp/pm-base.tar
        docker image ls -a
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: Dockerfile
        pull: true
        push: false
        load: true
        tags: pm:4.1.21-test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Check Image
      run: |
        docker pull processmaker/pm4-core:4.1.21
        docker image ls
        docker image inspect pm:4.1.21
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

