name: Docker Image CI

on:
  push:
    paths:
      - Dockerfile.base
      - .github/workflows/base-test.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
    - name: Build and push
        id: docker_build
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: Dockerfile.base
        pull: true
        push: false
        tags: pm-base:4.1-test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Check Image
      run: |
        docker pull processmaker/pm4-base:1.0.0
        docker image ls
        #docker image inspect pm-base:4.1-test
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
