name: Docker Image CI

on:
  push:
    branches: [ optimize ]
  pull_request:
    branches: [ optimize ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.base --tag pm-base:4.1-test
    - name: Check Image
      run: docker image ls
