name: Sail
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: processmaker/processmaker
          ref: refs/tags/v4.1.21
      - name: Setup PHP
        uses: shivammathur/setup-php@2.17.0
        with:
          # Setup PHP version.
          php-version: 7.4
          # Setup PHP extensions.
          extensions: # optional
          # Set base ini file.
          ini-file: # optional, default is production
          # Add values to php.ini.
          ini-values: # optional
          # Setup code coverage driver.
          coverage: # optional
          # Setup popular tools globally.
          tools: # optional
      - name: Install Sail
        run: |
          composer require laravel/sail --dev
          composer update
          php artisan sail:install
      - uses: actions/upload-artifact@v2.3.1
        with:
          path: .
