name: Sail
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: processmaker/processmaker
          ref: refs/tags/v4.1.21
      - name: Setup PHP
        uses: shivammathur/setup-php@2.17.0
        with:
          php-version: '7.4'
#      - name : test
#        run: |
#          docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php74-composer:latest composer install --ignore-platform-reqs
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: test
#        run: |
#          rm -rf composer.lock
      - name: Install Sail
        run: |
          sed 's/\~5\.7\.0\|\~5\.8\.0\|\^6\.0/\^8\.0/g' composer.lock
          sed 's/6\.18\.31\|\^7\.22\.4/\^8\.0/g' composer.lock
          sed 's/\~5\.4\.0\|\~5\.5\.0\|\~5\.6\.0\|\~5\.7\.0\|\~5\.8\.0\|\^6\.0\|\^7\.0/\^8\.0/g' composer.lock
          sed 's/\~5\.0/\^8\.0/g' composer.lock
          sed 's/\~\5\.4\|\^6\.0\|\^7\.0/\^8\.0/g' composer.lock
          sed 's/\>\= 5\.4\.0/\^8\.0/g' composer.lock
          composer require laravel/sail --dev
          composer update
          php artisan sail:install
      - uses: actions/upload-artifact@v2.3.1
        with:
          path: .
