name: Sail
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: processmaker/processmaker
          ref: refs/tags/v4.1.21
      - name: Setup PHP
        uses: shivammathur/setup-php@2.17.0
        with:
        php-version: '7.4'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Install Sail
        run: |
          composer require laravel/sail --dev
          composer update
          php artisan sail:install
      - uses: actions/upload-artifact@v2.3.1
        with:
          path: .
